env:
  global:
    - HOME="RolePlayingGame"

language: java
install: true

os: linux
dist: trusty
jdk: oraclejdk8

notifications:
  email:
    recipients:
      - andrea.giuntini@stud.unifi.it
    on_success: never # default: change
    on_failure: always # default: always

addons:
  sonarcloud:
    organization: "andreagiuntiniunifi"
    token:
      secure: "8cf12f067cac87452addb49d090f796d5ce8decb" # encrypted value of your token

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_script: cd $HOME/

script:
  - ./gradlew build --scan -s
  - ./gradlew sonarqube
after_success:
  - ./gradlew jacocoTestReport coveralls
